### ISSUE TITLE
Suggestion: Add TOC to blog HTML template

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slateci.github.io#179]
This is a suggestion to add a headings-based TOC to the blog HTML template.

**Comment by jstidd** [comment]
If doing this, we would need javascript to pull out the headings, create links, and add those to the top. This may be more work than it is worth. If a blog post needs a TOC, it may be easier to add one in markdown as needed rather than automating it. A lot of blog posts won't be as large as the upgrade document blog post we created.
